### ISSUE TITLE
[BUG]: Duplicated keys in Recommended which-key mappings

### ISSUE THREAD

**Issue by jamesiain** [2KAbhishek/termim.nvim#1]
### Description of the bug

In the **Recommended which-key mappings** section of **README.md**, it seems that the keymapping **te** is assigned to initiate both Elixer and Lazygit commands.

I suspect that the Lazygit command is in error, and should be mapped to **tg** instead.

### Steps To Reproduce

1. Go to the README.md (either in text or as rendered in a web browser)
2. Note that there are two entries with the same keymapping (Elixer, and Lazygit)

### Additional Information

<img width="890" alt="duplicate-keymapping" src="https://github.com/2KAbhishek/termim.nvim/assets/25421078/575ebc07-b750-4cdd-b576-ade2141da988">

Screenshot highlighting the line to be changed; it should probably start with "g = ", instead of "e = ".

**Comment by 2KAbhishek** [comment]
Thanks for identifying this @jamesiain! I'll push out a fix
