### ISSUE TITLE
NVIM 0.10 integration

### ISSUE THREAD

**Issue by sleeptightAnsiC** [2KAbhishek/termim.nvim#5]
### Description

Hey @2KAbhishek , 

Take a look at [NVIM 0.10 patch notes](https://neovim.io/doc/user/news-0.10.html). They've changed default terminal behavior. You may want to adjust the plugin a bit. For example, this can potentially break some cases:

```md
# Terminal:
* Terminal buffers started with no arguments (and use ['shell'](https://neovim.io/doc/user/options.html#'shell')) close automatically if the job exited without error, eliminating the (often unwanted) "[Process exited 0]" message. [default-autocmds](https://neovim.io/doc/user/vim_diff.html#default-autocmds)
```

**Comment by 2KAbhishek** [comment]
Hey @sleeptightAnsiC, thanks for the suggestion

I have started exploring this and will be patching it, as soon as I get some time.

Appreciate you setting up the issue, ty!

**Comment by 2KAbhishek** [comment]
After testing the plugin for the last week with nvim 0.10, I am comfortable closing this, things are functioning well
