### ISSUE TITLE
[Suggestion]: Chage cursor style in terminal mode

### ISSUE THREAD

**Issue by xronin01** [2KAbhishek/termim.nvim#6]
### Description

My cursor is I-beam in insert mode, but when I enter a terminal it always becomes a block.
Can you make the cursor change in terminal mode?

**Comment by 2KAbhishek** [comment]
This is something handled by core neovim and probably doesn't have a clean solution to change with plugins, 

I suggest checking the following links if you want to explore more:
https://github.com/neovim/neovim/issues/6005
https://github.com/wincent/terminus
